repos:
  - repo: local
    hooks:
      - id: ruff
        name: Ruff (local)
        entry: ruff check . # Command to run Ruff
        language: system  # Use the system Python environment
        types: [python]  # Specify file types to check

      - id: black
        name: Black (local)
        entry: black . # Command to run Black
        language: system  # Use the system Python environment
        types: [python]  # Specify file types to check
