repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        name: Ruff
        entry: ruff check src/recommender tests # Command to run Ruff
        language: system  # Use the system Python environment
        types: [python]  # Specify file types to check

  - repo: local
    hooks:
      - id: black
        name: Black (local)
        entry: black src/recommender tests # Command to run Black
        language: system  # Use the system Python environment
        types: [python]  # Specify file types to check